@localhost = http://localhost:8080

#####
# @name createTopic
POST {{localhost}}/kafka/topic HTTP/1.1
Content-Type: application/json

{
    "topicName": "quickstart-events",
    "partitions": 1,
    "replicationFactor": 1
}

#####
# @name produceRecord
POST {{localhost}}/kafka/record/publish/quickstart-events HTTP/1.1

#####
# @name consumeRecord
GET {{localhost}}/kafka/record/consume/quickstart-events HTTP/1.1
